### PR TITLE
Addding Tinkers Construct recipes for Alloy Smelter

### PR DESCRIPTION
**Pull request by hron84**
These recipes are directly from Tinkers Construct. They are technically
done, but maybe needs some more balancing in energy consumption.

### CODE REVIEW

**Comment by MrKunji** [comment]
Endstone is not balanced, in Tinkers' is one Ender Pearl plus five Obsidian for five Endstone, or one Ender Pearl plus one Sandstone for one Endstone.

**Comment by HenryLoenwind** [comment]
The obsidian recipe is has its amounts reversed. Easy to fix.

**Comment by hron84** [comment]
@MrKunji I think it is changed then since I committed that change. I will take look again when I have a chance. I would like to ask a bit patience, because my laptop is currently being repaired.

**Comment by tterrag1098** [comment]
As per #2418 I am changing my mind on this

**Pull request closed without merging**
