### PR TITLE
Fix minor IItemRenderer bugs, closes #1718

### LINKED ISSUE #1718: [Minor] Many render "bugs" in EnderIO
It's a minor bug: Most machines render wrong as thrown item, in the hand, in the inventory and more.
Minor minor bug: 1. EnderIO machines face to the wrong way in the inventory, should face to the right.
2. Machines as item render too far from the "shader".
3. Some machines render large in the hand.
4. Some machines render away from the hand.
5. Machines render too far up in the inventory.
6. Some Machines in the F5 mode render wrong.
7. More, probaly ;)

Screenshots: http://imgur.com/a/G2ooA
Those are minor bugs but they are bugs ;)! Also sorry for my bad English, I'm German!

### PR DESCRIPTION
**Pull request by TheJulianJES**
This should fix #1718, also other creative tabs shouldn't blink anymore (blinking: https://imgur.com/a/Gils7)
If I can anything improve in my PR, just tell me :)

### CODE REVIEW

**Comment by TheJulianJES** [comment]
If you want to get some screenshots, I can post some of the fixed renders. Just tell me. ;)

**Comment by MatthiasMann** [comment]
You should not change the formatting of code

**Comment by TheJulianJES** [comment]
Okay, I could probaly change it, but it was just a mess...

**Comment by TheJulianJES** [comment]
I fixed the formattiong as @MatthiasMann requested. It was hard.

**Comment by TheJulianJES** [comment]
I fixed the formattiong as @MatthiasMann requested. It was hard.

**Comment by tterrag1098** [comment]
Your formatting is all over the place, please use the provided format XML file.

Also, I would prefer to leave the effect on the enderface.

**Comment by TheJulianJES** [comment]
@tterrag1098 1. I will try it
                       2. Enderface bugs and make other tabs invisible, see my images.

**Comment by TheJulianJES** [comment]
For some reason I can't squash the latest two commits, can you maybe help me, sorry and thank's..

**Comment by TheJulianJES** [comment]
So I fixed formatting, I guess? @tterrag1098 Is this good now :D?

**Comment by Adaptivity** [comment]
@tterrag1098 will it be in 2.3 version? I'm interested in blinking tabs fix.

**Comment by TheJulianJES** [comment]
@Adaptivity They don't like to have the Creative Icon unenchanted, the reset of this PR I have to fix soon :)

**Comment by CrazyPants** [comment]
Whats happening with this? Should I just close this PR and then you can open a fresh one once its sorted?

**Comment by TheJulianJES** [comment]
Yea, probaly good...

**Pull request closed without merging**
