### PR TITLE
Update zh_TW.lang

### PR DESCRIPTION
**Pull request by ibmibmibm**

### CODE REVIEW

**Comment by Uptobillion** [comment]
我也在做翻译 第一次上github 请问这个失败的原因是什么呢？

**Comment by xsun2001** [comment]
这是因为java8与java7的差异导致的。
https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/render/util/QuadCollector.java 这个文件中的一个内部类 `BlockRenderLayerIterator` 实现了 `Iterator` 接口，但是没有实现 `remove` 方法，这在java8中是允许的，因为 `remove` 方法这个版本中是个 `default` 方法，也就是说它不一定要被实现，但是java7中没有这个特性，导致编译失败。

**Comment by Uptobillion** [comment]
谢谢

**Comment by 3TUSK** [comment]
@xsun2001 Um, if you had said so in English, travis ci could have not failed on each time of new pull request being opened because someone can fix this. Or would you like to open a new one?

**Comment by HenryLoenwind** [comment]
The Travis build was set up for 1.7.10, it doesn't quite work for 1.10.2. We got so few PRs that we never bothered fixing it...

**Pull request closed without merging**
