### PR TITLE
Fix Block Detector

### LINKED ISSUE #5000: Block Detector output is inverted
#### Issue Description:

As a rule, vanilla Minecraft switches emit redstone only when activated. The Block Detector is basically a pressure plate for blocks. So, I would expect a redstone signal to be emitted only when a block is detected.

#### What happens:
A redstone signal is emitted until a block is detected.

#### What you expected to happen:
A redstone signal to be emitted only when a block is detected.

#### Steps to reproduce:

1. Place Block Detector.
2. Place Redstone near Block Detector.
3. Observe that the redstone is active without a block being detected.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.38
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768-universal
- SpongeForge? no
- Optifine? no
- Single player and server.

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/2726002/latest.log)

### PR DESCRIPTION
**Pull request by StackDoubleFlow**
Should fix #5000

### CODE REVIEW

**Comment by StackDoubleFlow** [comment]
Alright

**Comment by StackDoubleFlow** [comment]
I added it to the config now

**Comment by HenryLoenwind** [comment]
You also need to put in models that have some kind of counter lever that reverses the direction of the upper and lower part of the box that blocks the redstone signal from the internal redstone block.

**Comment by StackDoubleFlow** [comment]
Does the current model not work?

**Comment by StackDoubleFlow** [comment]
Closing since the issue was closed.

**Pull request closed without merging**
