### PR TITLE
Update and rename resources/assets/enderio/lang/zh_CN.lang to 资源/资产/e…

### PR DESCRIPTION
**Pull request by PeakXing**
…nderio/郎/zh_CN.lang

Add translation
Change description error character

### CODE REVIEW

**Comment by Vexatos** [comment]
You must not change the file structure...

**Comment by HenryLoenwind** [comment]
those changes make no sense at in for 1.7.10

**Comment by 3TUSK** [comment]
And that is the result of machine translator. Even the path got translated as well...

**Comment by 3TUSK** [comment]
@Vexatos Sounds not fun at all... ZeroNoRyouki/BigReactors#3
Time to investigate. @Mrkwtkr

**Pull request closed without merging**
