### PR TITLE
Update ru_ru.lang

### PR DESCRIPTION
**Pull request by Bytegm**
Fixed more mistakes.
Configuration strings untouched

### CODE REVIEW

**Comment by Bytegm** [comment]
Can I find out what's wrong here?

**Comment by HenryLoenwind** [comment]
Nothing wrong here other that I cannot read Russian and was waiting for people from The Discord to comment on this. I'll ask them again.

**Comment by Bytegm** [comment]
> Nothing wrong here other that I cannot read Russian and was waiting for people from The Discord to comment on this. I'll ask them again.

ok, I will wait for an answer

**Comment by Bytegm** [comment]
@HenryLoenwind, well what's up there?

**Pull request closed without merging**
