### PR TITLE
Enchanter COFH, Draconic Evolution, EnderZoo Support

### PR DESCRIPTION
**Pull request by tyler489**

### CODE REVIEW

**Comment by EpicSquid** [comment]
If we are to add this it would probably be best to make a new recipe file for modded enchanter recipes, similar to the sagmill.

**Comment by tyler489** [comment]
If you wish.

**Comment by HenryLoenwind** [comment]
split of not doesn't matter to me, we can move recipes around now without any worries. But I'm not ok with the itemSkull change. First you now got a conflict between those 2 recipes, and then we should not change old recipes without very good reason. People know them and expect them to stay the same.

**Comment by tyler489** [comment]
No because tormented endermand head doesnt extend itemskull in game. But i can change it back

**Comment by tyler489** [comment]
Ill fix vorpal when i get home. Any ideas on  what to use?

**Comment by tyler489** [comment]
Obsid will work.

**Pull request merged**
