### PR TITLE
Update Forge and fix Fluid API

### PR DESCRIPTION
**Pull request by wasweb**
It should be done sooner or later. 
Untested!

### CODE REVIEW

**Comment by MatthiasMann** [comment]
Why did you make an untested PR? Just test it before creating the PR.

**Comment by wasweb** [comment]
I mean it's working for me. I just warn you guys to check it out before merging it.

**Comment by tterrag1098** [comment]
I would rather not force a forge update, we currently only require a very old version of forge, and I see no reason to make this change.

**Comment by TheJulianJES** [comment]
@tterrag1098 Since it will crash with newer forge versions.

**Comment by tterrag1098** [comment]
@TheJulianJES No it won't.

**Comment by TheJulianJES** [comment]
@tterrag1098 O_o

**Pull request closed without merging**
