### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by xMrVizzy**

### CODE REVIEW

**Comment by xMrVizzy** [comment]
@HenryLoenwind why no one check pull request?

**Comment by xMrVizzy** [comment]
@tterrag1098 @HenryLoenwind who can answer on my question?

**Comment by xMrVizzy** [comment]
oh shit

**Comment by HenryLoenwind** [comment]
As none of us are speaking Russian, we're giving people who do a chance to see this and comment on it.

**Comment by xMrVizzy** [comment]
@HenryLoenwind https://github.com/SleepyTrousers/EnderIO/pull/3390

**Comment by xMrVizzy** [comment]
Believe me, the old translation is REAAAAAAAALY SHIT.

**Comment by xMrVizzy** [comment]
Feeling that he was doing from 2 year old child

**Comment by xMrVizzy** [comment]
For example in old translate (non mine) some string has (Перевёрнутый) whats mean (Flipped), but in English translate is (Inverted) is (Инвертированный). 

And old translate has many like this errors

**Pull request closed without merging**
