### PR TITLE
Elevator functionality and sneak activation

### PR DESCRIPTION
**Pull request by Lilylicious**
Solves the "issue" in #2296 where jump enhancements/flight can cause difficulties in activating travel anchors and/or cause increased iteration periods between attempts.

### CODE REVIEW

**Comment by tterrag1098** [comment]
This should probably have a config. It is client-sided after all.

**Comment by Dwargkiller** [comment]
Please be patient while I sort out the mess I made.

**Comment by Dwargkiller** [comment]
Pull request is finalized. Features outlined below:

1) Elevator functionality. If there is no valid selected target, it tries to select one above (if jump is used) or below (if sneak is used) within range. 
2) Adds sneak as an activation for targeted teleportation, with config option to disable it (default true)
3) Adds a configurable cooldown for travel anchors (default 0 ticks), though without any graphical representation of said cooldown.

**Comment by Dwargkiller** [comment]
Did some work regarding access modes with vertical teleports:

1) If the possible target requires password and is NOT private (an unowned private anchor returns true on getRequiresPassword, owned returns false), open the password GUI. It does not do anything further, future attempts will open the gui if password was unsuccessful while teleporting if it was successful, as with other teleports.

2) Now skips private anchors it can't access as well as obstructed anchors.

TODO/Thoughts:

a) Add messages for skip events (Skipped obstructed anchor.. etc)
b) Make the password gui attempt teleportation on success and skip in vertical search if closed without success. Not sure how the password gui is handled and if it provides any hooks for open/close success/failure states.

**Comment by eduardog3000** [comment]
Couldn't you change getRequiresPassword() from: 

```Java
@Override
  public boolean getRequiresPassword(EntityPlayer username) {
    return getAccessMode() != AccessMode.PUBLIC && !canUiBeAccessed(username) && !authorisedUsers.contains(PlayerUtil.getPlayerUUID(username.getGameProfile().getName()));
  }
```

to:

```Java
@Override
  public boolean getRequiresPassword(EntityPlayer username) {
    return getAccessMode() == AccessMode.PROTECTED && !canUiBeAccessed(username) && !authorisedUsers.contains(PlayerUtil.getPlayerUUID(username.getGameProfile().getName()));
  }
```

I don't see where a password would be required for anything but protected anyways.

**Comment by Dwargkiller** [comment]
@eduardog3000 I'm planning to take a stab at reworking some of the ambiguity and edge cases in the anchor code, though I'll do that separate from this PR.

**Comment by Dwargkiller** [comment]
Recent changes:

1) Locked travel anchors no longer provide gui. They are instead skipped in the search for targets when doing an elevator teleport.
2) A skipped anchor now produces a chat message.
3) Some cleanup of redundancy in functions (TileTravelAnchor)

**Comment by eduardog3000** [comment]
I guess rebasing made our commit comments about OpenBlocks support disappear from this page, so I'm gonna link it here for future reference.

https://github.com/Lilylicious/EnderIO/commit/246eff7f7cf5afe13144d546eaf57e39dd723649#commitcomment-10817064

**Pull request merged**
