### PR TITLE
Added magicalcrops_MagicalCropFertilizer

### PR DESCRIPTION
**Pull request by HenryLoenwind**

### CODE REVIEW

**Comment by Adaptivity** [comment]
What about MineFactoryReloaded Industrial Fertilizer?

**Comment by HenryLoenwind** [comment]
@Adaptivity If it cannot be right-clicked on a crop it has to wait. I'll do those later, because I have to find out their "potency" in comparison to bone meal.

No sense in wasting a super-duper-ultra fertilizer that takes 5 dragon eggs to craft and can fertilize whole dimensions to grow a single wheat by one phase. ;)

**Comment by tterrag1098** [comment]
Please go with a smaller enum name...lol

**Comment by HenryLoenwind** [comment]
I was tempted to use "M", but couldn't bring myself to do so. ;)

**Pull request merged**
