### PR TITLE
Updated ru_ru.lang (+after release)

### PR DESCRIPTION
**Pull request by kellixon**
I fully translated the mod EnderIO (version 5.0.20) to Russian language. Source of took from file en_us.lang (1674 lines). Could you give me en_us.lang file, when you upload the next build, so I checked the line and gave you a ready-made Russian language file.

### CODE REVIEW

**Comment by tyler489** [comment]
the file to be changed should be ru_ru.lang

**Comment by tyler489** [comment]
you are also missing a few new items such as 
Line 24 item.item_alloy_ingot_end_steel.name=End Steel Ingot 
Line 34 item.item_alloy_ball_end_steel.name=End Steel Grinding Ball 
Line 44 item.item_alloy_nugget_end_steel.name=End Steel Nugget

**Comment by tyler489** [comment]
In addition everything after ```# Conduits``` needs to be split up into each "submod" .lang section and posted in there not in enderio-base

**Comment by kellixon** [comment]
Made. #conduits #base #machines #toolmaterialnames #forestry.
#InvPanel need?

**Comment by tyler489** [comment]
not in this file

**Comment by kellixon** [comment]
OK. Issue closed

**Pull request closed without merging**
