### PR TITLE
Don't crash if in MP a client doesn't have another player's profile loaded

### PR DESCRIPTION
**Pull request by HenryLoenwind**
re #2743

### CODE REVIEW

**Comment by HenryLoenwind** [comment]
This may not be the root cause, but null checking seldom hurts...

**Comment by MrNuggelz** [comment]
The Execption seems to come from the EntityPlaye being null. I altered your code, to check if the player is null:
GameProfile gameProfile = player == null ? null : player.getGameProfile();
Since then the exception didn't occur.

**Comment by HenryLoenwind** [comment]
Thx for testing, I adapted the PR to accommodate that case.

**Comment by tterrag1098** [comment]
Have you tested this on a server to be sure that the controls still function?

**Comment by MrNuggelz** [comment]
I have it running on my MP server and i haven't found a problem. Controlls work fine.

**Pull request merged**
