### PR TITLE
Feature/enchanter

### PR DESCRIPTION
**Pull request by Rover656**
# Description

The Enchanter machine.
Mainly need some comments on the recipe, if the fields are correct for what we want to achieve.

Fixes issue(s): # (issue)

# Todo 

- [x] Merge Rover656/EnderIO-Rewrite#29 
- [ ] Enchanter Block model
- [x] All recipes

# Checklist:

- [x] My code follows the style guidelines of this project (.editorconfig, most IDEs will use this for you)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Rover656** [comment]
Will merge once checks pass.

**Comment by ferriarnus** [comment]
> This pull request **introduces 1 alert** when merging [818dca4](https://github.com/SleepyTrousers/EnderIO/commit/818dca45e50f8bb0756023fb6393217a6b868b3d) into [0928834](https://github.com/SleepyTrousers/EnderIO/commit/09288348e38f59046e7f3a7e00af8939b43cee5c) - [view on LGTM.com](https://lgtm.com/projects/g/SleepyTrousers/EnderIO/rev/pr-d2583bd75c4a0c3e7e3abe3027a35cf2052b272f)
> 
> **new alerts:**
> 
> * 1 for Dereferenced variable may be null

This seems really useful. The null check may indeed be to late.

**Comment by Rover656** [comment]
Yeah thats very useful!

**Comment by Rover656** [comment]
Huh, this is an obsolete PR.

**Pull request closed without merging**
