### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by xMrVizzy**

### CODE REVIEW

**Comment by xMrVizzy** [comment]
@CrazyPants @HenryLoenwind merge yourself ignor Travis CI error, please

**Comment by xMrVizzy** [comment]
Hello?!

**Comment by HenryLoenwind** [comment]
just the usual, all of us are afraid to merge languages they don't speak. It will be merged, give it some time.

**Comment by xMrVizzy** [comment]
It's error because Java 7 doesn't want build :(
screenshot_1

**Comment by xMrVizzy** [comment]
How can i fix it error with Travis CI?

**Comment by xMrVizzy** [comment]
Authors of this mod @HenryLoenwind, @CrazyPants and others, I really like this mod and i want make RU translate will be updated. But i can't make it still due Travis CI check! Can you answer on my question: How can i fix it, or can you merge it yourself without this check?

Thanks for the next feedback!

**Comment by xMrVizzy** [comment]
Thank you, @tterrag1098!

**Comment by HenryLoenwind** [comment]
btw, the CI failure has nothing to do with your PR. It seems the Travis Java 1.7 build always dies atm. Low prio for now.

**Pull request merged**
