### PR TITLE
Refactored Item and Block init

### PR DESCRIPTION
**Pull request by HenryLoenwind**

### CODE REVIEW

**Comment by Nick-77ab2** [comment]
contains merge conflicts that must be resolved?

**Comment by HenryLoenwind** [comment]
@Nick-77ab2 You're welcome to do so ;)

@tterrag1098 Tell me if you want to pull this, I'll merge it once then.

**Comment by Nick-77ab2** [comment]
oh, i was just confused on why there's conflicts, and i'm not really good at programming at all as i'm pretty much just finishing VB.Net at my school xD and haven't taken java and other classes yet.

**Comment by tterrag1098** [comment]
I think I'll be doing this differently when I attempt the modularization later down the road

**Pull request closed without merging**
