### PR TITLE
EE3 EMC values

### PR DESCRIPTION
**Pull request by HenryLoenwind**
* Added EE3 EMC values
* Fixed reversed ender pearl dust registration logic
* re #2817

### CODE REVIEW

**Comment by tterrag1098** [comment]
I refuse to believe this code is safe without EE3 installed...everything I know says it's not.

**Comment by HenryLoenwind** [comment]
It is. It only contains calls to static methods, those are not inspected until they are actually executed. No field or local variables of some unloaded type, not interfaces, no inheritance. Basically the same thing as calls to a @sideonly-removed method.

    INVOKESTATIC com/pahimar/ee3/api/exchange/EnergyValueRegistryProxy.addPreAssignedEnergyValue (Ljava/lang/Object;F)V

**Comment by tterrag1098** [comment]
But you are executing them without checking if EE3 is loaded. the `if (IS_EE3_LOADED)` check is sufficient??

**Comment by HenryLoenwind** [comment]
as it is

    public static final boolean IS_EE3_LOADED = Loader.isModLoaded(EE3_ID);

it should be. I could throw in a check for the API version, but that'd make us the only mod to do so.

And yes, I have studied about every mod that uses the ee3 api and can be found by Google. Had to, to get an idea how to even use that thing.

**Comment by tterrag1098** [comment]
What I'm saying is that it was my understanding that when a method is invoked, all references are resolved. Why is this not the case here?

**Comment by HenryLoenwind** [comment]
Because there is no reference to any object there. Only an INVOKESTATIC that takes one parameter, the fully qualified name of the *static* method to invoke. Or to quote the spec: "after the invokestatic opcode is a 16-bit unsigned integer index. This is the index of an entry in the constant pool." which contains a CONSTANT_Methodref entry which points to a CONSTANT_Class entry, all of which only contain references to CONSTANT_Utf8_info values. ( https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html ) So the actual class lookup/loading only happens when the INVOKESTATIC is actually executed and the Strings are resolved into class and field objects. Until that time, they are only IDs into the constant pool and Strings in it.

An INVOKEVIRTUAL (non-static method call) would be different. There an object to call the method on has to exist in the calling context, even if it isn't explicitly assigned to a variable. You can see that in the actual com.pahimar.ee3.api.exchange.EnergyValueRegistryProxy.addPreAssignedEnergyValue() method. There the call is dispatched to an object (API -> mod), but an additional layer of indirection must be used for this to work.

**Comment by tterrag1098** [comment]
Ok, fine, I *guess* I believe you now :stuck_out_tongue:

**Pull request merged**
