### PR TITLE
Spawners get nasty when broken

### PR DESCRIPTION
**Pull request by HenryLoenwind**
At least a little bit

### CODE REVIEW

**Comment by tterrag1098** [comment]
What does this fix?

**Comment by HenryLoenwind** [comment]
Did I tag this "fix"? Nope, it's an enhancement.

Reasoning: People are more and more doing "break spawner fast, then deal with mobs" instead of the traditional "light up area, kill mobs, break spawner". And as EIO already meddles with spawners...

**Comment by tterrag1098** [comment]
Oh! It spawns mobs when it's broken. I like that, yes.

**Comment by HenryLoenwind** [comment]
Oh, yes. That method is not obvious from its name

**Pull request merged**
