### PR TITLE
Add Thaumaturge's Armor vis discount upgrades.

### PR DESCRIPTION
**Pull request by eduardog3000**
Add Thaumaturge's Armor vis discount upgrades for Dark Steel Armor.

### CODE REVIEW

**Comment by eduardog3000** [comment]
Actually, let me add some localization in other languages first.

**Comment by eduardog3000** [comment]
Alright, I copied localizations for "Thaumaturge's [Robe/Leggings/Boots]" from Thaumcraft, and copied the localization for "Vis Discount" from the tooltip of the Revealing upgrade.

**Comment by tterrag1098** [comment]
Why add duplicate lang entries instead of just using Thaumcraft's? We know it is installed when this is active.

**Comment by eduardog3000** [comment]
Hmm, I didn't even think of that. I'll change that and rebase.

**Comment by eduardog3000** [comment]
Done, but the tooltip has to be `item.ItemChestplateRobe.tooltip.detailed.line1` rather than following the standard `enderio.darksteel.upgrade.thaumaturgeArmor.chestplate.tooltip.detailed.line1`.

**Comment by tterrag1098** [comment]
I think this is better left out, we don't want to completely re-implement TC's armor, EIO armor can do enough as it is.

**Pull request closed without merging**
