### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**
This update is for `1.9` branch.

### CODE REVIEW

**Comment by xMrVizzy** [comment]
Unfortunately i think it can't be uploaded like my ru update due travis-ci check!

**Comment by 3TUSK** [comment]
No, it can be merged.  
See the info below, said "only those who can push commit to this repository can merge this pull request".  
Failing in CI doesn't means that this pull request can't be merged - only merge conflict does so.

**Comment by 3TUSK** [comment]
Also, even if this pull request couldn't not be merged via Github webpage, manually merging will do it.

**Comment by 3TUSK** [comment]
Close it - will redo for latest version.

**Pull request closed without merging**
