### PR TITLE
Fixed spelling, some grammar, and a lot of formatting

### PR DESCRIPTION
**Pull request by tgstyle**
I have made the SAGMill xml a little easier to read and a bit of cleanup.

### CODE REVIEW

**Comment by MatthiasMann** [comment]
Why did you remove all the blank lines?

**Comment by tgstyle** [comment]
Consistency, a lot of the config had no lines between the recipes already. The lines are now between the recipe groups.

**Comment by tterrag1098** [comment]
Could you compress this to one (or two) commits?

**Comment by tgstyle** [comment]
Sure, I will have to figure it out.

**Comment by tterrag1098** [comment]
https://github.com/SleepyTrousers/EnderIO/pull/1692#issuecomment-70351606

**Comment by tgstyle** [comment]
OK I think I got it.

**Pull request merged**
