### PR TITLE
Re-add ComputerCraft bundled cable integration

### PR DESCRIPTION
**Pull request by SquidDev**
Effectively cherry-picked from #1208. I'm not sure if this is a) wanted and b) how mod integration is meant to be handled, so feel free to close it :).

One thing worth noting is that `IRedstoneConduit.getNetworkOutputs` has the side parameter annotated as `@Nonnull`, but handles `null` arguments (which is required here in order to return the signal for all colours).

### CODE REVIEW

**Comment by EpicSquid** [comment]
I definitely have been wanting to add this! Thank you. I will check it over properly later. Main thing to note, which computer craft fork at this point will this be officially supporting?

**Comment by SquidDev** [comment]
> Main thing to note, which computer craft fork at this point will this be officially supporting?

It should support all of them, as the API hasn't diverged (yet!). It's currently just building off the master branch of the original repo, as I'd consider that the a good mix of official and stable, though I'm happy to switch it to use the latest Curse release instead.

**Comment by EpicSquid** [comment]
No need to change it, I'll look into this soon

**Comment by SquidDev** [comment]
Thanks!

**Comment by EpicSquid** [comment]
No worries

**Pull request merged**
