### PR TITLE
Add some more Hoes to Farming Station whitelist

### LINKED ISSUE #2952: Farming station does not accept Thermal Foundation Hoes
Hoes added by Thermal Foundation (Copper, Bronze, etc.) cannot be put into a Farming Station. I assume that this is a bug since TF Axes and Shears work without a problem.

EnderIO 1.7.10-2.3.0.417_beta
EnderCore 1.7.10-0.1.0.26_beta
CoFH Core 3.0.3
Thermal Foundation 1.2.0

### PR DESCRIPTION
**Pull request by wlhlm**
Closes #2952

### CODE REVIEW

**Comment by wlhlm** [comment]
I've updated this PR include the Draconic Hoe, as well as some Hoes from Twilight Forest and one from IC2. I did some quick tests and they all seam to behave as expected without breaking anything (crashes, etc.).

I think this is ready.

**Comment by tterrag1098** [comment]
Does this list include any unbreakable hoes? I was leaving those out on purpose.

**Comment by HenryLoenwind** [comment]
The comment in the config is a bit vague. Did we leave out all unbreakables, or just those unbreakables that actually do break?

In the first case: Maybe we should have a second list with unbreakable hoes and a flag to allow them in?

**Comment by wlhlm** [comment]
Hmm, not sure if it's exactly what you mean, but I just checked again, and I'm not sure about the Draconic Hoe...

The thing is, the Draconic Hoe normally runs off of RF and can be recharged. It can till a huge area all at once. When put inside a Farming Station, it works as normal, but it'll still work once its charge is depleted. I guess that makes it "unbreakable".

Should I remove it? By the time you are able to craft a Draconic Hoe (it requires killing several Withers and the Ender Dragon), does it really matter if it is unbreakable or not?

The rest of added Hoes are all "breakable".

**Comment by tterrag1098** [comment]
No, it's a balance concern. people can add unbreakable hoes if they want, but I don't want them to be allowed by default.

**Comment by wlhlm** [comment]
Fair enough. I removed it. The rest should be fine.

**Comment by wlhlm** [comment]
BTW, how does this work for axes (and Shears for that matter)? They don't seem to use a black/whitelist, and so I'm able to put a Draconic Axe (which works similar to the Draconic Hoe) into the Farming Station and it'll still work when depleted. Why do hoes have to be balanced and Axes/Shears not?

**Comment by tterrag1098** [comment]
Axes (and other tools) have methods to determine what tool type they are. Hoes aren't actually tools, they are just items that do something on right click.

**Comment by HenryLoenwind** [comment]
Ah, you know how it is. One day you may decide something, but you never go back over what you did in the past and adapt it to that decision...

**Comment by wlhlm** [comment]
\*nudge\* \*nudge\*

**Comment by HenryLoenwind** [comment]
Here? I had to nudge tt  in IRC while hovering my mouse over the "build" button for those simple fixes yesterday. He's very busy atm, give him time. This PR is not forgotten.

**Pull request merged**
