### PR TITLE
#1712 #880 More enchants for enchanter

### PR DESCRIPTION
**Pull request by Adaptivity**
Soul stealer enchantment should be ok
CoFH enchantment catalysts doesn't really makes sense but... they are good for me. If anyone can suggest better catalysts I can change them. But keep in mind that they are should be from TE/TF/TD mods.
Holding uses Compressed Sawdust
Multishot uses 2 Slags

### CODE REVIEW

**Comment by tterrag1098** [comment]
What even are those items? Why not use oredict?

**Comment by Adaptivity** [comment]
Soul stealer -> Soul shard
Holding -> Compressed Sawdust
Multishot -> 2 Slags
Are they oredicted? They are not oredicted in TE.

**Comment by Adaptivity** [comment]
So... what do you think?

**Comment by Yulife** [comment]
Is it done the same way in TE or what does multishots have to do with a byproduct of an induction furnace o_o

**Comment by Adaptivity** [comment]
Is TE have catalysts for their enchants? I don't think so. The main problem is that catalysts should be from CoFH mods (They can be from vanilla too but CrazyPants recommended to use them from mods). And I don't know which items will fit better. If you can suggest better catalysts, go ahead, I'll change them.

**Comment by Yulife** [comment]
Multishot: Aerotheum Dust, Oredict is "dustAerotheum"
Holding: Reinforced Strongbox, Modname: ThermalExpansion; Item Name: Strongbox; Metadata: 3

**Comment by Adaptivity** [comment]
@tterrag1098 should say final word.

**Comment by tterrag1098** [comment]
How is aerotheum made?

**Comment by cloakable** [comment]
One sandstone, one blitz powder (Thermal Foundation mob), one redstone, one niter gives two aerotheum dust.

**Comment by tterrag1098** [comment]
Aerotheum seems reasonable for multishot, and I also like the strongbox for holding, though it seems a bit redundant (since it only goes on strongboxes and satchels) :P

**Comment by Adaptivity** [comment]
So, should I update this?

**Comment by tterrag1098** [comment]
Yes

**Pull request closed without merging**
