### PR TITLE
RU: Updated Translate

### PR DESCRIPTION
**Pull request by xMrVizzy**
Added:
- Nutritious Stick
- Vapor of Levity
- Precient Crystal, Precient Powder
- Inventory Panel Sensor
- Dialing Device
- Skeletal Contractor
- Dark Steel Bow
- Exit Rail
- Self Resetting Lever

### CODE REVIEW

**Comment by xMrVizzy** [comment]
@HenryLoenwind one more update :)

**Comment by xMrVizzy** [comment]
Update it please :)

**Comment by xMrVizzy** [comment]
Hey, SleepyTrousers owners, can you give me push access, i can't make a Russian translate because you merge so slowly :(

**Comment by xMrVizzy** [comment]
10 updates!!!!!!!!!!!!!!!!!!!!!!!!! @tterrag1098 @CrazyPants @HenryLoenwind

**Comment by xMrVizzy** [comment]
Please click one button to merge!!!

**Comment by xMrVizzy** [comment]
@tterrag1098 @CrazyPants @HenryLoenwind !

**Comment by xMrVizzy** [comment]
@HenryLoenwind hey!

**Comment by xMrVizzy** [comment]
@tterrag1098 @CrazyPants @HenryLoenwind can you merge 11 more commits! :)

**Comment by KamranMackey** [comment]
@xMrVizzy Squash your commits please. They won't merge a billion commits into the repository.

You can squash commits with this git command:

`git rebase -i HEAD~numberofcommits`, in this instance `numberofcommits` would be 11, then just do a force git push. 

Make sure you delete ALL commit summaries in the squash confirm window. I don't think they want a long ass commit summary with 11 commit titles and descriptions.

Also, stop pinging all the members of the organization. They most likely don't like being pinged.

**Comment by KamranMackey** [comment]
@xMrVizzy I've made multiple revisions to my comment. Make sure you open the response in your browser instead of reading it via email as it'll be outdated.

**Comment by tterrag1098** [comment]
@KamranMackey Squashing is not necessary and has not been for some time now. Github has this ability available when merging a PR.

**Comment by KamranMackey** [comment]
Oh. Right. They implemented that ability a while back. I totally forgot. My
bad!

**Comment by xMrVizzy** [comment]
Okay, but why no merge?

**Comment by KamranMackey** [comment]
@xMrVizzy Maybe because it isn't needed at the moment? PR's don't have to be merged immediately after you create them.

**Comment by xMrVizzy** [comment]
@KamranMackey About this "Also, stop pinging all the members of the organization. They most likely don't like it. One more thing, do NOT ask for push access. If I'm correct, they only give people push access when they can trust them and they've made a significant amount of contributions."

I know pinging all the members of the organization is not good, but annoying me that other mod authors to whom I send my Russian localisation respond quickly, but EnderIO authors ignore me now more than 1.5 months!

**Comment by HenryLoenwind** [comment]
Two reasons:

1. I was giving other Russian speakers the chance to look at this and tell us if there's some problems. I don't speak Russian and cannot say if your translations are good or not. (We did have some bad PRs for lang files in the past.)
2. I tend to forget doing these things

**Comment by xMrVizzy** [comment]
@HenryLoenwind yes, I can say you, that my translation is quality. fromgate is my friend, he Officialy translate Minecraft!

**Comment by xMrVizzy** [comment]
If I do something I can not translate that happens rarely, I appeal to him!

**Comment by KamranMackey** [comment]
@xMrVizzy Who's fromgate?

**Comment by xMrVizzy** [comment]
@KamranMackey Russian Approover on Crowdin, he made more then 75% of translate yourself and update it every new Minecraft Version quickly

**Comment by xMrVizzy** [comment]
He is a realy good!

**Pull request merged**
