### PR TITLE
Aluminum Support

### PR DESCRIPTION
**Pull request by Dwargkiller**
Sag Mill Aluminum oredict support

### CODE REVIEW

**Comment by Adaptivity** [comment]
What about Aluminium? It is same to Aluminum but some mods uses Aluminium name.

**Comment by tterrag1098** [comment]
@Adaptivity Then those mods are wrong. Ore dictionary is done in american english, that's the standard.

**Comment by Vexatos** [comment]
@tterrag1098 Not really, considering the proper scientific term is Aluminium, even in American English. Aluminum is just the more common term there.

**Comment by tterrag1098** [comment]
@Vexatos regardless of technicalities, the majority of mods already use "um", so I see no need to support doube-standards.

**Comment by Adaptivity** [comment]
@tterrag1098 there are an issue open for that: https://github.com/SleepyTrousers/EnderIO/issues/307 so it still might worth adding Aluminium.

**Pull request merged**
