### PR TITLE
Added Additional Hooks to make it easier to add Custom Conduits

### PR DESCRIPTION
**Pull request by spacebuilder2020**
Make a few modifications that would prevent crashes when trying to use a custom conduit class implementing IConduit with a custom network.

Also, made it easier to extend AbstractItemConduit for creating items for your Conduits.

### CODE REVIEW

**Comment by spacebuilder2020** [comment]
I am working on a mod that will add ic2 and GT conduits, and I was running into crashes when trying to use a custom network with a custom conduit.

**Comment by HenryLoenwind** [comment]
About the modObject, in Ender IO Addons I use

    public static final ModObject ModObject_blockxxx = EnumHelper.addEnum(ModObject.class, "blockxxx", new Class<?>[0], new Object[0]);

just FYI

**Comment by spacebuilder2020** [comment]
Yea, the reason I used reflection in the createNetworkForType() instead of adding a new method to I Conduit is because I did not want it to break existing code.

**Comment by spacebuilder2020** [comment]
Closed cause I am rewriting the createNetworkForType method based on the above suggestions.

**Pull request closed without merging**
