### PR TITLE
Various null checks

### PR DESCRIPTION
**Pull request by HenryLoenwind**
Some potential NPEs, some impossible null checks, some reordering to get
rid of null warnings, and even one or two logic errors

### CODE REVIEW

**Comment by tterrag1098** [comment]
I don't like unnecessary null checks, something being null where it shouldn't be is a bug elsewhere.

**Comment by HenryLoenwind** [comment]
With the exception of one or two "oh compiler shut up"-null checks, all new null checks are on paths where null is a valid value.

BTW: Isn't that a lovely pearl of 'what's my line?':

         if(cb != null) {
           totalStored += cb.doGetEnergyStored();
         }
         ItemStack[] inv = cb.inventory;

;)

**Comment by tterrag1098** [comment]
Regardless I'd prefer if this was split into multiple commits or even PRs. "logic errors" doesn't describe what you changed.

**Comment by HenryLoenwind** [comment]
ok, I'll divide it up. np

**Pull request closed without merging**
