### PR TITLE
Potentialy fix incompatibily with diet hoppers in 1.12

### PR DESCRIPTION
**Pull request by tyler489**
Rwtema said to use Blocks.Hopper or  forge "IRegistryDelegate"

### CODE REVIEW

**Comment by tyler489** [comment]
Even if this doesnt fix it it will make the code match the item filters using blockHopper

**Comment by HenryLoenwind** [comment]
We are using `Blocks.HOPPER`. If @rwtema breaks this one, they are really doing something wrong.

**Comment by tyler489** [comment]
We call blockhopper for item filter but minecraft:hopper for the impulse hopper.

**Comment by HenryLoenwind** [comment]
not a fix

**Pull request closed without merging**
